import { BUILTIN_TOOL_DEFINITIONS } from './builtin'
import { WORD_TOOL_DEFINITIONS } from './word'
import { PDF_TOOL_DEFINITIONS } from './pdf'
import { PPTX_TOOL_DEFINITIONS } from './pptx'
import { MAIL_TOOL_DEFINITIONS } from './mail'

export const TOOL_DEFINITIONS = [
  ...BUILTIN_TOOL_DEFINITIONS,
  ...WORD_TOOL_DEFINITIONS,
  ...PDF_TOOL_DEFINITIONS,
  ...PPTX_TOOL_DEFINITIONS,
  ...MAIL_TOOL_DEFINITIONS
]

export {
  BUILTIN_TOOL_DEFINITIONS,
  WORD_TOOL_DEFINITIONS,
  PDF_TOOL_DEFINITIONS,
  PPTX_TOOL_DEFINITIONS,
  MAIL_TOOL_DEFINITIONS
}
